package com.nj.model.activiti.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProcessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public ProcessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdIsNull() {
            addCriterion("process_template_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdIsNotNull() {
            addCriterion("process_template_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdEqualTo(String value) {
            addCriterion("process_template_id =", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdNotEqualTo(String value) {
            addCriterion("process_template_id <>", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdGreaterThan(String value) {
            addCriterion("process_template_id >", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_template_id >=", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdLessThan(String value) {
            addCriterion("process_template_id <", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdLessThanOrEqualTo(String value) {
            addCriterion("process_template_id <=", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdLike(String value) {
            addCriterion("process_template_id like", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdNotLike(String value) {
            addCriterion("process_template_id not like", value, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdIn(List<String> values) {
            addCriterion("process_template_id in", values, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdNotIn(List<String> values) {
            addCriterion("process_template_id not in", values, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdBetween(String value1, String value2) {
            addCriterion("process_template_id between", value1, value2, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andProcessTemplateIdNotBetween(String value1, String value2) {
            addCriterion("process_template_id not between", value1, value2, "processTemplateId");
            return (Criteria) this;
        }

        public Criteria andBmpnNameIsNull() {
            addCriterion("bmpn_name is null");
            return (Criteria) this;
        }

        public Criteria andBmpnNameIsNotNull() {
            addCriterion("bmpn_name is not null");
            return (Criteria) this;
        }

        public Criteria andBmpnNameEqualTo(String value) {
            addCriterion("bmpn_name =", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameNotEqualTo(String value) {
            addCriterion("bmpn_name <>", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameGreaterThan(String value) {
            addCriterion("bmpn_name >", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameGreaterThanOrEqualTo(String value) {
            addCriterion("bmpn_name >=", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameLessThan(String value) {
            addCriterion("bmpn_name <", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameLessThanOrEqualTo(String value) {
            addCriterion("bmpn_name <=", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameLike(String value) {
            addCriterion("bmpn_name like", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameNotLike(String value) {
            addCriterion("bmpn_name not like", value, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameIn(List<String> values) {
            addCriterion("bmpn_name in", values, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameNotIn(List<String> values) {
            addCriterion("bmpn_name not in", values, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameBetween(String value1, String value2) {
            addCriterion("bmpn_name between", value1, value2, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andBmpnNameNotBetween(String value1, String value2) {
            addCriterion("bmpn_name not between", value1, value2, "bmpnName");
            return (Criteria) this;
        }

        public Criteria andPngNameIsNull() {
            addCriterion("png_name is null");
            return (Criteria) this;
        }

        public Criteria andPngNameIsNotNull() {
            addCriterion("png_name is not null");
            return (Criteria) this;
        }

        public Criteria andPngNameEqualTo(String value) {
            addCriterion("png_name =", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameNotEqualTo(String value) {
            addCriterion("png_name <>", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameGreaterThan(String value) {
            addCriterion("png_name >", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameGreaterThanOrEqualTo(String value) {
            addCriterion("png_name >=", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameLessThan(String value) {
            addCriterion("png_name <", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameLessThanOrEqualTo(String value) {
            addCriterion("png_name <=", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameLike(String value) {
            addCriterion("png_name like", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameNotLike(String value) {
            addCriterion("png_name not like", value, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameIn(List<String> values) {
            addCriterion("png_name in", values, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameNotIn(List<String> values) {
            addCriterion("png_name not in", values, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameBetween(String value1, String value2) {
            addCriterion("png_name between", value1, value2, "pngName");
            return (Criteria) this;
        }

        public Criteria andPngNameNotBetween(String value1, String value2) {
            addCriterion("png_name not between", value1, value2, "pngName");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdIsNull() {
            addCriterion("deployment_id is null");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdIsNotNull() {
            addCriterion("deployment_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdEqualTo(String value) {
            addCriterion("deployment_id =", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotEqualTo(String value) {
            addCriterion("deployment_id <>", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdGreaterThan(String value) {
            addCriterion("deployment_id >", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdGreaterThanOrEqualTo(String value) {
            addCriterion("deployment_id >=", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdLessThan(String value) {
            addCriterion("deployment_id <", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdLessThanOrEqualTo(String value) {
            addCriterion("deployment_id <=", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdLike(String value) {
            addCriterion("deployment_id like", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotLike(String value) {
            addCriterion("deployment_id not like", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdIn(List<String> values) {
            addCriterion("deployment_id in", values, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotIn(List<String> values) {
            addCriterion("deployment_id not in", values, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdBetween(String value1, String value2) {
            addCriterion("deployment_id between", value1, value2, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotBetween(String value1, String value2) {
            addCriterion("deployment_id not between", value1, value2, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdIsNull() {
            addCriterion("processdef_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdIsNotNull() {
            addCriterion("processdef_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdEqualTo(String value) {
            addCriterion("processdef_id =", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdNotEqualTo(String value) {
            addCriterion("processdef_id <>", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdGreaterThan(String value) {
            addCriterion("processdef_id >", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdGreaterThanOrEqualTo(String value) {
            addCriterion("processdef_id >=", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdLessThan(String value) {
            addCriterion("processdef_id <", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdLessThanOrEqualTo(String value) {
            addCriterion("processdef_id <=", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdLike(String value) {
            addCriterion("processdef_id like", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdNotLike(String value) {
            addCriterion("processdef_id not like", value, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdIn(List<String> values) {
            addCriterion("processdef_id in", values, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdNotIn(List<String> values) {
            addCriterion("processdef_id not in", values, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdBetween(String value1, String value2) {
            addCriterion("processdef_id between", value1, value2, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessdefIdNotBetween(String value1, String value2) {
            addCriterion("processdef_id not between", value1, value2, "processdefId");
            return (Criteria) this;
        }

        public Criteria andProcessVersionIsNull() {
            addCriterion("process_version is null");
            return (Criteria) this;
        }

        public Criteria andProcessVersionIsNotNull() {
            addCriterion("process_version is not null");
            return (Criteria) this;
        }

        public Criteria andProcessVersionEqualTo(Integer value) {
            addCriterion("process_version =", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionNotEqualTo(Integer value) {
            addCriterion("process_version <>", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionGreaterThan(Integer value) {
            addCriterion("process_version >", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("process_version >=", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionLessThan(Integer value) {
            addCriterion("process_version <", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionLessThanOrEqualTo(Integer value) {
            addCriterion("process_version <=", value, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionIn(List<Integer> values) {
            addCriterion("process_version in", values, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionNotIn(List<Integer> values) {
            addCriterion("process_version not in", values, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionBetween(Integer value1, Integer value2) {
            addCriterion("process_version between", value1, value2, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("process_version not between", value1, value2, "processVersion");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIsNull() {
            addCriterion("process_key is null");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIsNotNull() {
            addCriterion("process_key is not null");
            return (Criteria) this;
        }

        public Criteria andProcessKeyEqualTo(String value) {
            addCriterion("process_key =", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotEqualTo(String value) {
            addCriterion("process_key <>", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyGreaterThan(String value) {
            addCriterion("process_key >", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyGreaterThanOrEqualTo(String value) {
            addCriterion("process_key >=", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLessThan(String value) {
            addCriterion("process_key <", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLessThanOrEqualTo(String value) {
            addCriterion("process_key <=", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLike(String value) {
            addCriterion("process_key like", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotLike(String value) {
            addCriterion("process_key not like", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIn(List<String> values) {
            addCriterion("process_key in", values, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotIn(List<String> values) {
            addCriterion("process_key not in", values, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyBetween(String value1, String value2) {
            addCriterion("process_key between", value1, value2, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotBetween(String value1, String value2) {
            addCriterion("process_key not between", value1, value2, "processKey");
            return (Criteria) this;
        }

        public Criteria andNamespaceIsNull() {
            addCriterion("namespace is null");
            return (Criteria) this;
        }

        public Criteria andNamespaceIsNotNull() {
            addCriterion("namespace is not null");
            return (Criteria) this;
        }

        public Criteria andNamespaceEqualTo(String value) {
            addCriterion("namespace =", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceNotEqualTo(String value) {
            addCriterion("namespace <>", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceGreaterThan(String value) {
            addCriterion("namespace >", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceGreaterThanOrEqualTo(String value) {
            addCriterion("namespace >=", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceLessThan(String value) {
            addCriterion("namespace <", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceLessThanOrEqualTo(String value) {
            addCriterion("namespace <=", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceLike(String value) {
            addCriterion("namespace like", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceNotLike(String value) {
            addCriterion("namespace not like", value, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceIn(List<String> values) {
            addCriterion("namespace in", values, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceNotIn(List<String> values) {
            addCriterion("namespace not in", values, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceBetween(String value1, String value2) {
            addCriterion("namespace between", value1, value2, "namespace");
            return (Criteria) this;
        }

        public Criteria andNamespaceNotBetween(String value1, String value2) {
            addCriterion("namespace not between", value1, value2, "namespace");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionIsNull() {
            addCriterion("product_process_version is null");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionIsNotNull() {
            addCriterion("product_process_version is not null");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionEqualTo(Integer value) {
            addCriterion("product_process_version =", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionNotEqualTo(Integer value) {
            addCriterion("product_process_version <>", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionGreaterThan(Integer value) {
            addCriterion("product_process_version >", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_process_version >=", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionLessThan(Integer value) {
            addCriterion("product_process_version <", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionLessThanOrEqualTo(Integer value) {
            addCriterion("product_process_version <=", value, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionIn(List<Integer> values) {
            addCriterion("product_process_version in", values, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionNotIn(List<Integer> values) {
            addCriterion("product_process_version not in", values, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionBetween(Integer value1, Integer value2) {
            addCriterion("product_process_version between", value1, value2, "productProcessVersion");
            return (Criteria) this;
        }

        public Criteria andProductProcessVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("product_process_version not between", value1, value2, "productProcessVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table process
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 28 10:42:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table process
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}