package com.nj.dao.esign.mapper.base;

import com.nj.model.esign.base.EsignCoporateAccount;
import com.nj.model.esign.base.EsignCoporateAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsignCoporateAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int countByExample(EsignCoporateAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int deleteByExample(EsignCoporateAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int insert(EsignCoporateAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int insertSelective(EsignCoporateAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    List<EsignCoporateAccount> selectByExample(EsignCoporateAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") EsignCoporateAccount record, @Param("example") EsignCoporateAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esign_coporate_account
     *
     * @mbggenerated Wed Dec 13 14:32:36 CST 2017
     */
    int updateByExample(@Param("record") EsignCoporateAccount record, @Param("example") EsignCoporateAccountExample example);
}