package com.nj.dao;

import com.nj.core.base.mapper.BaseMapper;
import com.nj.model.generate.BlackStock;
import com.nj.model.generate.BlackStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlackStockMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int countByExample(BlackStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int deleteByExample(BlackStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int insert(BlackStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int insertSelective(BlackStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    List<BlackStock> selectByExample(BlackStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    BlackStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlackStock record, @Param("example") BlackStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int updateByExample(@Param("record") BlackStock record, @Param("example") BlackStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int updateByPrimaryKeySelective(BlackStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_stock
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    int updateByPrimaryKey(BlackStock record);
}