package com.nj.dao;

import com.nj.core.base.mapper.BaseMapper;
import com.nj.model.generate.ChannelStock;
import com.nj.model.generate.ChannelStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelStockMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int countByExample(ChannelStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int deleteByExample(ChannelStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int insert(ChannelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int insertSelective(ChannelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    List<ChannelStock> selectByExample(ChannelStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    ChannelStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChannelStock record, @Param("example") ChannelStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int updateByExample(@Param("record") ChannelStock record, @Param("example") ChannelStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int updateByPrimaryKeySelective(ChannelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock
     *
     * @mbggenerated Tue Jul 28 10:55:57 CST 2020
     */
    int updateByPrimaryKey(ChannelStock record);
}