package com.nj.dao;

import com.nj.core.base.mapper.BaseMapper;
import com.nj.model.generate.ErrorErpOrderModel;
import com.nj.model.generate.ErrorErpOrderModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorErpOrderModelMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int countByExample(ErrorErpOrderModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int deleteByExample(ErrorErpOrderModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int insert(ErrorErpOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int insertSelective(ErrorErpOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    List<ErrorErpOrderModel> selectByExample(ErrorErpOrderModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    ErrorErpOrderModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") ErrorErpOrderModel record, @Param("example") ErrorErpOrderModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int updateByExample(@Param("record") ErrorErpOrderModel record, @Param("example") ErrorErpOrderModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int updateByPrimaryKeySelective(ErrorErpOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_erp_order_model
     *
     * @mbggenerated Thu Jul 30 11:12:13 CST 2020
     */
    int updateByPrimaryKey(ErrorErpOrderModel record);
}