package com.nj.dao;

import com.nj.model.generate.NjCoporateUser;
import com.nj.model.generate.NjCoporateUserExample;
import com.nj.model.generate.NjCoporateUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjCoporateUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	long countByExample(NjCoporateUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int deleteByExample(NjCoporateUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int deleteByPrimaryKey(NjCoporateUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int insert(NjCoporateUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int insertSelective(NjCoporateUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	List<NjCoporateUser> selectByExample(NjCoporateUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	NjCoporateUser selectByPrimaryKey(NjCoporateUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NjCoporateUser record,
			@Param("example") NjCoporateUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int updateByExample(@Param("record") NjCoporateUser record, @Param("example") NjCoporateUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int updateByPrimaryKeySelective(NjCoporateUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_coporate_user
	 * @mbg.generated  Tue Apr 11 13:56:03 CST 2017
	 */
	int updateByPrimaryKey(NjCoporateUser record);

	void updateByPrimaryKey2(NjCoporateUser njCoporateUser);
}