package com.nj.dao;

import com.nj.model.generate.NjMessage;
import com.nj.model.generate.NjMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	long countByExample(NjMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByExample(NjMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insert(NjMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insertSelective(NjMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	List<NjMessage> selectByExample(NjMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	NjMessage selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NjMessage record, @Param("example") NjMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExample(@Param("record") NjMessage record, @Param("example") NjMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKeySelective(NjMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_message
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKey(NjMessage record);
}