package com.nj.dao;

import com.nj.model.generate.NjProductEvent;
import com.nj.model.generate.NjProductEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjProductEventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	long countByExample(NjProductEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByExample(NjProductEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insert(NjProductEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insertSelective(NjProductEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	List<NjProductEvent> selectByExample(NjProductEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	NjProductEvent selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NjProductEvent record,
			@Param("example") NjProductEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExample(@Param("record") NjProductEvent record, @Param("example") NjProductEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKeySelective(NjProductEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_event
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKey(NjProductEvent record);
}