package com.nj.dao;

import com.nj.model.generate.NjProductTacticsProperty;
import com.nj.model.generate.NjProductTacticsPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjProductTacticsPropertyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	long countByExample(NjProductTacticsPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int deleteByExample(NjProductTacticsPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int insert(NjProductTacticsProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int insertSelective(NjProductTacticsProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	List<NjProductTacticsProperty> selectByExample(NjProductTacticsPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	NjProductTacticsProperty selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NjProductTacticsProperty record,
			@Param("example") NjProductTacticsPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int updateByExample(@Param("record") NjProductTacticsProperty record,
			@Param("example") NjProductTacticsPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int updateByPrimaryKeySelective(NjProductTacticsProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_tactics_property
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	int updateByPrimaryKey(NjProductTacticsProperty record);
}