package com.nj.dao;

import com.nj.model.generate.NjProductTransactionOffline;
import com.nj.model.generate.NjProductTransactionOfflineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjProductTransactionOfflineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	long countByExample(NjProductTransactionOfflineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int deleteByExample(NjProductTransactionOfflineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int insert(NjProductTransactionOffline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int insertSelective(NjProductTransactionOffline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	List<NjProductTransactionOffline> selectByExample(NjProductTransactionOfflineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	NjProductTransactionOffline selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NjProductTransactionOffline record,
			@Param("example") NjProductTransactionOfflineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int updateByExample(@Param("record") NjProductTransactionOffline record,
			@Param("example") NjProductTransactionOfflineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int updateByPrimaryKeySelective(NjProductTransactionOffline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_product_transaction_offline
	 * @mbg.generated  Tue Nov 14 17:19:06 CST 2017
	 */
	int updateByPrimaryKey(NjProductTransactionOffline record);
}