package com.nj.dao;

import com.nj.core.base.mapper.BaseMapper;
import com.nj.model.generate.NjStrategy;
import com.nj.model.generate.NjStrategyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NjStrategyMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int countByExample(NjStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int deleteByExample(NjStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int insert(NjStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int insertSelective(NjStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    List<NjStrategy> selectByExample(NjStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    NjStrategy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") NjStrategy record, @Param("example") NjStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int updateByExample(@Param("record") NjStrategy record, @Param("example") NjStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int updateByPrimaryKeySelective(NjStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_strategy
     *
     * @mbggenerated Thu Jul 16 14:38:04 CST 2020
     */
    int updateByPrimaryKey(NjStrategy record);
}