package com.nj.dao;

import com.nj.core.base.mapper.BaseMapper;
import com.nj.model.generate.StockFormat;
import com.nj.model.generate.StockFormatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockFormatMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int countByExample(StockFormatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int deleteByExample(StockFormatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int insert(StockFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int insertSelective(StockFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    List<StockFormat> selectByExample(StockFormatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    StockFormat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockFormat record, @Param("example") StockFormatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int updateByExample(@Param("record") StockFormat record, @Param("example") StockFormatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int updateByPrimaryKeySelective(StockFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format
     *
     * @mbggenerated Mon Jul 27 11:11:17 CST 2020
     */
    int updateByPrimaryKey(StockFormat record);
}