package com.nj.dao;

import com.nj.model.generate.SysRoleResource;
import com.nj.model.generate.SysRoleResourceExample;
import com.nj.model.generate.SysRoleResourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	long countByExample(SysRoleResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByExample(SysRoleResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int deleteByPrimaryKey(SysRoleResourceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insert(SysRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int insertSelective(SysRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	List<SysRoleResource> selectByExample(SysRoleResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	SysRoleResource selectByPrimaryKey(SysRoleResourceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysRoleResource record,
			@Param("example") SysRoleResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByExample(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_resource
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	int updateByPrimaryKey(SysRoleResource record);
}