package com.nj.dao;

import com.nj.model.generate.SysUserRole;
import com.nj.model.generate.SysUserRoleExample;
import com.nj.model.generate.SysUserRoleKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	long countByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int deleteByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int deleteByPrimaryKey(SysUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int insert(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int insertSelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	List<SysUserRole> selectByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	SysUserRole selectByPrimaryKey(SysUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int updateByExample(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated  Thu Mar 09 10:52:44 CST 2017
	 */
	int updateByPrimaryKey(SysUserRole record);
	
	
	int deleteByUserId(Map<?, ?> condition);
	
	int insertBatch(List list);
}