package com.nj.dao;

import com.nj.model.generate.UserZhimaIvsScore;
import com.nj.model.generate.UserZhimaIvsScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserZhimaIvsScoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	long countByExample(UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int deleteByExample(UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int insert(UserZhimaIvsScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int insertSelective(UserZhimaIvsScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	List<UserZhimaIvsScore> selectByExampleWithBLOBs(UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	List<UserZhimaIvsScore> selectByExample(UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	UserZhimaIvsScore selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserZhimaIvsScore record,
			@Param("example") UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") UserZhimaIvsScore record,
			@Param("example") UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByExample(@Param("record") UserZhimaIvsScore record, @Param("example") UserZhimaIvsScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByPrimaryKeySelective(UserZhimaIvsScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(UserZhimaIvsScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_zhima_ivs_score
	 * @mbg.generated  Mon Mar 27 19:22:32 CST 2017
	 */
	int updateByPrimaryKey(UserZhimaIvsScore record);
}