package com.nj.dao.activiti.mapper.base;

import com.nj.model.activiti.base.ProcessTemplateConfig;
import com.nj.model.activiti.base.ProcessTemplateConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessTemplateConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int countByExample(ProcessTemplateConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int deleteByExample(ProcessTemplateConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int insert(ProcessTemplateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int insertSelective(ProcessTemplateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    List<ProcessTemplateConfig> selectByExample(ProcessTemplateConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    ProcessTemplateConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProcessTemplateConfig record, @Param("example") ProcessTemplateConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByExample(@Param("record") ProcessTemplateConfig record, @Param("example") ProcessTemplateConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByPrimaryKeySelective(ProcessTemplateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_template_config
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByPrimaryKey(ProcessTemplateConfig record);
}