package com.nj.dao.activiti.mapper.base;

import com.nj.model.activiti.base.ProcessUsertaskRole;
import com.nj.model.activiti.base.ProcessUsertaskRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessUsertaskRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int countByExample(ProcessUsertaskRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int deleteByExample(ProcessUsertaskRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int insert(ProcessUsertaskRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int insertSelective(ProcessUsertaskRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    List<ProcessUsertaskRole> selectByExample(ProcessUsertaskRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProcessUsertaskRole record, @Param("example") ProcessUsertaskRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_usertask_role
     *
     * @mbggenerated Fri Jul 28 10:42:09 CST 2017
     */
    int updateByExample(@Param("record") ProcessUsertaskRole record, @Param("example") ProcessUsertaskRoleExample example);
}