package com.nj.dao.activiti.mapper.base;

import com.nj.model.activiti.base.ProcessFormTaskins;
import com.nj.model.activiti.base.ProcessFormTaskinsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessFormTaskinsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int countByExample(ProcessFormTaskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int deleteByExample(ProcessFormTaskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int insert(ProcessFormTaskins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int insertSelective(ProcessFormTaskins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    List<ProcessFormTaskins> selectByExample(ProcessFormTaskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProcessFormTaskins record, @Param("example") ProcessFormTaskinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_form_taskins
     *
     * @mbggenerated Thu Sep 14 10:20:38 CST 2017
     */
    int updateByExample(@Param("record") ProcessFormTaskins record, @Param("example") ProcessFormTaskinsExample example);
}