package com.nj.model.generate;

public class BlackStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_stock.id
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_stock.stock_no
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    private String stockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_stock.size_range
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    private String sizeRange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_stock.id
     *
     * @return the value of black_stock.id
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_stock.id
     *
     * @param id the value for black_stock.id
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_stock.stock_no
     *
     * @return the value of black_stock.stock_no
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public String getStockNo() {
        return stockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_stock.stock_no
     *
     * @param stockNo the value for black_stock.stock_no
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public void setStockNo(String stockNo) {
        this.stockNo = stockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_stock.size_range
     *
     * @return the value of black_stock.size_range
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public String getSizeRange() {
        return sizeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_stock.size_range
     *
     * @param sizeRange the value for black_stock.size_range
     *
     * @mbggenerated Mon Oct 26 18:33:16 CST 2020
     */
    public void setSizeRange(String sizeRange) {
        this.sizeRange = sizeRange;
    }
}