package com.nj.model.generate;

public class NjAcceptThresholds {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.product_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.sys_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.thre_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer threType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.custom_mobile
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String customMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_accept_thresholds.thre_status
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer threStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.id
	 * @return  the value of nj_accept_thresholds.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.id
	 * @param id  the value for nj_accept_thresholds.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.product_id
	 * @return  the value of nj_accept_thresholds.product_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.product_id
	 * @param productId  the value for nj_accept_thresholds.product_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.sys_id
	 * @return  the value of nj_accept_thresholds.sys_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.sys_id
	 * @param sysId  the value for nj_accept_thresholds.sys_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.thre_type
	 * @return  the value of nj_accept_thresholds.thre_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getThreType() {
		return threType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.thre_type
	 * @param threType  the value for nj_accept_thresholds.thre_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setThreType(Integer threType) {
		this.threType = threType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.custom_mobile
	 * @return  the value of nj_accept_thresholds.custom_mobile
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getCustomMobile() {
		return customMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.custom_mobile
	 * @param customMobile  the value for nj_accept_thresholds.custom_mobile
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCustomMobile(String customMobile) {
		this.customMobile = customMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_accept_thresholds.thre_status
	 * @return  the value of nj_accept_thresholds.thre_status
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getThreStatus() {
		return threStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_accept_thresholds.thre_status
	 * @param threStatus  the value for nj_accept_thresholds.thre_status
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setThreStatus(Integer threStatus) {
		this.threStatus = threStatus;
	}
}