package com.nj.model.generate;

public class NjAppFeedback {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_app_feedback.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_app_feedback.feedback_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer feedbackType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_app_feedback.feedback_desc
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String feedbackDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_app_feedback.contact
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String contact;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_app_feedback.id
	 * @return  the value of nj_app_feedback.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_app_feedback.id
	 * @param id  the value for nj_app_feedback.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_app_feedback.feedback_type
	 * @return  the value of nj_app_feedback.feedback_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getFeedbackType() {
		return feedbackType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_app_feedback.feedback_type
	 * @param feedbackType  the value for nj_app_feedback.feedback_type
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setFeedbackType(Integer feedbackType) {
		this.feedbackType = feedbackType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_app_feedback.feedback_desc
	 * @return  the value of nj_app_feedback.feedback_desc
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getFeedbackDesc() {
		return feedbackDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_app_feedback.feedback_desc
	 * @param feedbackDesc  the value for nj_app_feedback.feedback_desc
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setFeedbackDesc(String feedbackDesc) {
		this.feedbackDesc = feedbackDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_app_feedback.contact
	 * @return  the value of nj_app_feedback.contact
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_app_feedback.contact
	 * @param contact  the value for nj_app_feedback.contact
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}
}