package com.nj.model.generate;

import java.util.ArrayList;
import java.util.List;

public class NjBankCodeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public NjBankCodeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNull() {
			addCriterion("bank_code is null");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNotNull() {
			addCriterion("bank_code is not null");
			return (Criteria) this;
		}

		public Criteria andBankCodeEqualTo(String value) {
			addCriterion("bank_code =", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotEqualTo(String value) {
			addCriterion("bank_code <>", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThan(String value) {
			addCriterion("bank_code >", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
			addCriterion("bank_code >=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThan(String value) {
			addCriterion("bank_code <", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThanOrEqualTo(String value) {
			addCriterion("bank_code <=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLike(String value) {
			addCriterion("bank_code like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotLike(String value) {
			addCriterion("bank_code not like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeIn(List<String> values) {
			addCriterion("bank_code in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotIn(List<String> values) {
			addCriterion("bank_code not in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeBetween(String value1, String value2) {
			addCriterion("bank_code between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotBetween(String value1, String value2) {
			addCriterion("bank_code not between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNoIsNull() {
			addCriterion("bank_no is null");
			return (Criteria) this;
		}

		public Criteria andBankNoIsNotNull() {
			addCriterion("bank_no is not null");
			return (Criteria) this;
		}

		public Criteria andBankNoEqualTo(String value) {
			addCriterion("bank_no =", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotEqualTo(String value) {
			addCriterion("bank_no <>", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoGreaterThan(String value) {
			addCriterion("bank_no >", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoGreaterThanOrEqualTo(String value) {
			addCriterion("bank_no >=", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLessThan(String value) {
			addCriterion("bank_no <", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLessThanOrEqualTo(String value) {
			addCriterion("bank_no <=", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoLike(String value) {
			addCriterion("bank_no like", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotLike(String value) {
			addCriterion("bank_no not like", value, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoIn(List<String> values) {
			addCriterion("bank_no in", values, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotIn(List<String> values) {
			addCriterion("bank_no not in", values, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoBetween(String value1, String value2) {
			addCriterion("bank_no between", value1, value2, "bankNo");
			return (Criteria) this;
		}

		public Criteria andBankNoNotBetween(String value1, String value2) {
			addCriterion("bank_no not between", value1, value2, "bankNo");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNull() {
			addCriterion("display_order is null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNotNull() {
			addCriterion("display_order is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderEqualTo(Integer value) {
			addCriterion("display_order =", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotEqualTo(Integer value) {
			addCriterion("display_order <>", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThan(Integer value) {
			addCriterion("display_order >", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("display_order >=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThan(Integer value) {
			addCriterion("display_order <", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
			addCriterion("display_order <=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIn(List<Integer> values) {
			addCriterion("display_order in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotIn(List<Integer> values) {
			addCriterion("display_order not in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
			addCriterion("display_order between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("display_order not between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andIsCommonIsNull() {
			addCriterion("is_common is null");
			return (Criteria) this;
		}

		public Criteria andIsCommonIsNotNull() {
			addCriterion("is_common is not null");
			return (Criteria) this;
		}

		public Criteria andIsCommonEqualTo(String value) {
			addCriterion("is_common =", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonNotEqualTo(String value) {
			addCriterion("is_common <>", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonGreaterThan(String value) {
			addCriterion("is_common >", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonGreaterThanOrEqualTo(String value) {
			addCriterion("is_common >=", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonLessThan(String value) {
			addCriterion("is_common <", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonLessThanOrEqualTo(String value) {
			addCriterion("is_common <=", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonLike(String value) {
			addCriterion("is_common like", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonNotLike(String value) {
			addCriterion("is_common not like", value, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonIn(List<String> values) {
			addCriterion("is_common in", values, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonNotIn(List<String> values) {
			addCriterion("is_common not in", values, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonBetween(String value1, String value2) {
			addCriterion("is_common between", value1, value2, "isCommon");
			return (Criteria) this;
		}

		public Criteria andIsCommonNotBetween(String value1, String value2) {
			addCriterion("is_common not between", value1, value2, "isCommon");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Boolean value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Boolean value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Boolean value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Boolean value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Boolean> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Boolean> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table nj_bank_code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nj_bank_code
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 15 14:14:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}