package com.nj.model.generate;

import java.util.Date;

public class NjConsumerLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.app_id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.output
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String output;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.biz_no
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String bizNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.create_date
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.nonce_str
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String nonceStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_consumer_log.input
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    private String input;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.id
     *
     * @return the value of nj_consumer_log.id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.id
     *
     * @param id the value for nj_consumer_log.id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.app_id
     *
     * @return the value of nj_consumer_log.app_id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.app_id
     *
     * @param appId the value for nj_consumer_log.app_id
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.output
     *
     * @return the value of nj_consumer_log.output
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.output
     *
     * @param output the value for nj_consumer_log.output
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setOutput(String output) {
        this.output = output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.biz_no
     *
     * @return the value of nj_consumer_log.biz_no
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.biz_no
     *
     * @param bizNo the value for nj_consumer_log.biz_no
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.create_date
     *
     * @return the value of nj_consumer_log.create_date
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.create_date
     *
     * @param createDate the value for nj_consumer_log.create_date
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.nonce_str
     *
     * @return the value of nj_consumer_log.nonce_str
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.nonce_str
     *
     * @param nonceStr the value for nj_consumer_log.nonce_str
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_consumer_log.input
     *
     * @return the value of nj_consumer_log.input
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public String getInput() {
        return input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_consumer_log.input
     *
     * @param input the value for nj_consumer_log.input
     *
     * @mbg.generated Thu Jul 20 15:11:54 CST 2017
     */
    public void setInput(String input) {
        this.input = input;
    }
}