package com.nj.model.generate;

public class NjHouseAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_house_attachment.id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_house_attachment.house_id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    private String houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_house_attachment.attachment_Id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    private String attachmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_house_attachment.id
     *
     * @return the value of nj_house_attachment.id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_house_attachment.id
     *
     * @param id the value for nj_house_attachment.id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_house_attachment.house_id
     *
     * @return the value of nj_house_attachment.house_id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_house_attachment.house_id
     *
     * @param houseId the value for nj_house_attachment.house_id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_house_attachment.attachment_Id
     *
     * @return the value of nj_house_attachment.attachment_Id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public String getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_house_attachment.attachment_Id
     *
     * @param attachmentId the value for nj_house_attachment.attachment_Id
     *
     * @mbg.generated Thu Jul 27 14:50:03 CST 2017
     */
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }
}