package com.nj.model.generate;

public class NjOrderUserinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_userinfo.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_userinfo.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_userinfo.basic_info_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String basicInfoId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_userinfo.id
	 * @return  the value of nj_order_userinfo.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_userinfo.id
	 * @param id  the value for nj_order_userinfo.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_userinfo.order_id
	 * @return  the value of nj_order_userinfo.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_userinfo.order_id
	 * @param orderId  the value for nj_order_userinfo.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_userinfo.basic_info_id
	 * @return  the value of nj_order_userinfo.basic_info_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getBasicInfoId() {
		return basicInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_userinfo.basic_info_id
	 * @param basicInfoId  the value for nj_order_userinfo.basic_info_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setBasicInfoId(String basicInfoId) {
		this.basicInfoId = basicInfoId;
	}
}