package com.nj.model.generate;

public class NjOrderUpdateAttachment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_update_attachment.id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_update_attachment.update_record_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	private Integer updateRecordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_update_attachment.attachment_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	private String attachmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_update_attachment.order_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	private String orderId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_update_attachment.id
	 * @return  the value of nj_order_update_attachment.id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_update_attachment.id
	 * @param id  the value for nj_order_update_attachment.id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_update_attachment.update_record_id
	 * @return  the value of nj_order_update_attachment.update_record_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public Integer getUpdateRecordId() {
		return updateRecordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_update_attachment.update_record_id
	 * @param updateRecordId  the value for nj_order_update_attachment.update_record_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public void setUpdateRecordId(Integer updateRecordId) {
		this.updateRecordId = updateRecordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_update_attachment.attachment_id
	 * @return  the value of nj_order_update_attachment.attachment_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public String getAttachmentId() {
		return attachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_update_attachment.attachment_id
	 * @param attachmentId  the value for nj_order_update_attachment.attachment_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public void setAttachmentId(String attachmentId) {
		this.attachmentId = attachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_update_attachment.order_id
	 * @return  the value of nj_order_update_attachment.order_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_update_attachment.order_id
	 * @param orderId  the value for nj_order_update_attachment.order_id
	 * @mbg.generated  Wed Apr 12 18:50:08 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}
}