package com.nj.model.generate;

public class NjOrderCert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_cert.id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_cert.order_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_cert.cert_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    private String certId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_cert.id
     *
     * @return the value of nj_order_cert.id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_cert.id
     *
     * @param id the value for nj_order_cert.id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_cert.order_id
     *
     * @return the value of nj_order_cert.order_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_cert.order_id
     *
     * @param orderId the value for nj_order_cert.order_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_cert.cert_id
     *
     * @return the value of nj_order_cert.cert_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public String getCertId() {
        return certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_cert.cert_id
     *
     * @param certId the value for nj_order_cert.cert_id
     *
     * @mbg.generated Fri Jul 28 14:12:13 CST 2017
     */
    public void setCertId(String certId) {
        this.certId = certId;
    }
}