package com.nj.model.generate;

import java.util.Date;

public class NjOrderHuoti {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.order_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.attachment_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private String attachmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.remark
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.type
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.version
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.del_flag
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.update_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.update_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.create_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti.create_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.id
     *
     * @return the value of nj_order_huoti.id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.id
     *
     * @param id the value for nj_order_huoti.id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.order_id
     *
     * @return the value of nj_order_huoti.order_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.order_id
     *
     * @param orderId the value for nj_order_huoti.order_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.attachment_id
     *
     * @return the value of nj_order_huoti.attachment_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public String getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.attachment_id
     *
     * @param attachmentId the value for nj_order_huoti.attachment_id
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.remark
     *
     * @return the value of nj_order_huoti.remark
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.remark
     *
     * @param remark the value for nj_order_huoti.remark
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.type
     *
     * @return the value of nj_order_huoti.type
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.type
     *
     * @param type the value for nj_order_huoti.type
     *
     * @mbg.generated Mon Jul 31 10:04:51 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.version
     *
     * @return the value of nj_order_huoti.version
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.version
     *
     * @param version the value for nj_order_huoti.version
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.del_flag
     *
     * @return the value of nj_order_huoti.del_flag
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.del_flag
     *
     * @param delFlag the value for nj_order_huoti.del_flag
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.update_date
     *
     * @return the value of nj_order_huoti.update_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.update_date
     *
     * @param updateDate the value for nj_order_huoti.update_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.update_by
     *
     * @return the value of nj_order_huoti.update_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.update_by
     *
     * @param updateBy the value for nj_order_huoti.update_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.create_date
     *
     * @return the value of nj_order_huoti.create_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.create_date
     *
     * @param createDate the value for nj_order_huoti.create_date
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti.create_by
     *
     * @return the value of nj_order_huoti.create_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti.create_by
     *
     * @param createBy the value for nj_order_huoti.create_by
     *
     * @mbg.generated Mon Jul 31 10:04:52 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
}