package com.nj.model.generate;

import java.util.Date;

public class NjOrderUpdateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.process_id
     *
     * @mbggenerated
     */
    private Integer processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.old_status
     *
     * @mbggenerated
     */
    private Integer oldStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.update_status
     *
     * @mbggenerated
     */
    private Integer updateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.update_channel
     *
     * @mbggenerated
     */
    private Integer updateChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.update_reason
     *
     * @mbggenerated
     */
    private String updateReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_update_log.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.id
     *
     * @return the value of nj_order_update_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.id
     *
     * @param id the value for nj_order_update_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.process_id
     *
     * @return the value of nj_order_update_log.process_id
     *
     * @mbggenerated
     */
    public Integer getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.process_id
     *
     * @param processId the value for nj_order_update_log.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.user_id
     *
     * @return the value of nj_order_update_log.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.user_id
     *
     * @param userId the value for nj_order_update_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.order_id
     *
     * @return the value of nj_order_update_log.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.order_id
     *
     * @param orderId the value for nj_order_update_log.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.old_status
     *
     * @return the value of nj_order_update_log.old_status
     *
     * @mbggenerated
     */
    public Integer getOldStatus() {
        return oldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.old_status
     *
     * @param oldStatus the value for nj_order_update_log.old_status
     *
     * @mbggenerated
     */
    public void setOldStatus(Integer oldStatus) {
        this.oldStatus = oldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.update_status
     *
     * @return the value of nj_order_update_log.update_status
     *
     * @mbggenerated
     */
    public Integer getUpdateStatus() {
        return updateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.update_status
     *
     * @param updateStatus the value for nj_order_update_log.update_status
     *
     * @mbggenerated
     */
    public void setUpdateStatus(Integer updateStatus) {
        this.updateStatus = updateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.update_channel
     *
     * @return the value of nj_order_update_log.update_channel
     *
     * @mbggenerated
     */
    public Integer getUpdateChannel() {
        return updateChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.update_channel
     *
     * @param updateChannel the value for nj_order_update_log.update_channel
     *
     * @mbggenerated
     */
    public void setUpdateChannel(Integer updateChannel) {
        this.updateChannel = updateChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.update_reason
     *
     * @return the value of nj_order_update_log.update_reason
     *
     * @mbggenerated
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.update_reason
     *
     * @param updateReason the value for nj_order_update_log.update_reason
     *
     * @mbggenerated
     */
    public void setUpdateReason(String updateReason) {
        this.updateReason = updateReason == null ? null : updateReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.update_date
     *
     * @return the value of nj_order_update_log.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.update_date
     *
     * @param updateDate the value for nj_order_update_log.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.remark
     *
     * @return the value of nj_order_update_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.remark
     *
     * @param remark the value for nj_order_update_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_update_log.remark2
     *
     * @return the value of nj_order_update_log.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_update_log.remark2
     *
     * @param remark2 the value for nj_order_update_log.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }
}