package com.nj.model.generate;

public class NjOrderWork {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_work.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_work.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_order_work.work_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String workId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_work.id
	 * @return  the value of nj_order_work.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_work.id
	 * @param id  the value for nj_order_work.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_work.order_id
	 * @return  the value of nj_order_work.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_work.order_id
	 * @param orderId  the value for nj_order_work.order_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_order_work.work_id
	 * @return  the value of nj_order_work.work_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getWorkId() {
		return workId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_order_work.work_id
	 * @param workId  the value for nj_order_work.work_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setWorkId(String workId) {
		this.workId = workId;
	}
}