package com.nj.model.generate;

import java.math.BigDecimal;
import java.util.Date;

public class NjOrderHuotiScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.order_id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.score
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.detail
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.source
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.del_flag
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.update_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.update_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.create_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.create_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_huoti_score.version
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.id
     *
     * @return the value of nj_order_huoti_score.id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.id
     *
     * @param id the value for nj_order_huoti_score.id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.order_id
     *
     * @return the value of nj_order_huoti_score.order_id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.order_id
     *
     * @param orderId the value for nj_order_huoti_score.order_id
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.score
     *
     * @return the value of nj_order_huoti_score.score
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.score
     *
     * @param score the value for nj_order_huoti_score.score
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.detail
     *
     * @return the value of nj_order_huoti_score.detail
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.detail
     *
     * @param detail the value for nj_order_huoti_score.detail
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.source
     *
     * @return the value of nj_order_huoti_score.source
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.source
     *
     * @param source the value for nj_order_huoti_score.source
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.del_flag
     *
     * @return the value of nj_order_huoti_score.del_flag
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.del_flag
     *
     * @param delFlag the value for nj_order_huoti_score.del_flag
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.update_by
     *
     * @return the value of nj_order_huoti_score.update_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.update_by
     *
     * @param updateBy the value for nj_order_huoti_score.update_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.update_date
     *
     * @return the value of nj_order_huoti_score.update_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.update_date
     *
     * @param updateDate the value for nj_order_huoti_score.update_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.create_by
     *
     * @return the value of nj_order_huoti_score.create_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.create_by
     *
     * @param createBy the value for nj_order_huoti_score.create_by
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.create_date
     *
     * @return the value of nj_order_huoti_score.create_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.create_date
     *
     * @param createDate the value for nj_order_huoti_score.create_date
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_huoti_score.version
     *
     * @return the value of nj_order_huoti_score.version
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_huoti_score.version
     *
     * @param version the value for nj_order_huoti_score.version
     *
     * @mbg.generated Mon Jul 31 10:05:09 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}