package com.nj.model.generate;

public class NjOrderUserCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_user_car.id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_user_car.order_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_order_user_car.user_car_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    private String userCarId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_user_car.id
     *
     * @return the value of nj_order_user_car.id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_user_car.id
     *
     * @param id the value for nj_order_user_car.id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_user_car.order_id
     *
     * @return the value of nj_order_user_car.order_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_user_car.order_id
     *
     * @param orderId the value for nj_order_user_car.order_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_order_user_car.user_car_id
     *
     * @return the value of nj_order_user_car.user_car_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public String getUserCarId() {
        return userCarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_order_user_car.user_car_id
     *
     * @param userCarId the value for nj_order_user_car.user_car_id
     *
     * @mbg.generated Thu Apr 27 14:09:16 CST 2017
     */
    public void setUserCarId(String userCarId) {
        this.userCarId = userCarId;
    }
}