package com.nj.model.generate;

public class NjProductRole extends NjProductRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_role.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_role.id
	 * @return  the value of nj_product_role.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_role.id
	 * @param id  the value for nj_product_role.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}
}