package com.nj.model.generate;

import java.util.Date;

public class NjProductTacticsProperty {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.tact_hand_id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String tactHandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.start_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String startVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.end_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String endVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.del_flag
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private Boolean delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.create_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.create_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.update_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_product_tactics_property.update_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.id
	 * @return  the value of nj_product_tactics_property.id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.id
	 * @param id  the value for nj_product_tactics_property.id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.tact_hand_id
	 * @return  the value of nj_product_tactics_property.tact_hand_id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getTactHandId() {
		return tactHandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.tact_hand_id
	 * @param tactHandId  the value for nj_product_tactics_property.tact_hand_id
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setTactHandId(String tactHandId) {
		this.tactHandId = tactHandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.start_val
	 * @return  the value of nj_product_tactics_property.start_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getStartVal() {
		return startVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.start_val
	 * @param startVal  the value for nj_product_tactics_property.start_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setStartVal(String startVal) {
		this.startVal = startVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.end_val
	 * @return  the value of nj_product_tactics_property.end_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getEndVal() {
		return endVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.end_val
	 * @param endVal  the value for nj_product_tactics_property.end_val
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setEndVal(String endVal) {
		this.endVal = endVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.del_flag
	 * @return  the value of nj_product_tactics_property.del_flag
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.del_flag
	 * @param delFlag  the value for nj_product_tactics_property.del_flag
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.create_date
	 * @return  the value of nj_product_tactics_property.create_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.create_date
	 * @param createDate  the value for nj_product_tactics_property.create_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.create_by
	 * @return  the value of nj_product_tactics_property.create_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.create_by
	 * @param createBy  the value for nj_product_tactics_property.create_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.update_date
	 * @return  the value of nj_product_tactics_property.update_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.update_date
	 * @param updateDate  the value for nj_product_tactics_property.update_date
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_product_tactics_property.update_by
	 * @return  the value of nj_product_tactics_property.update_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_product_tactics_property.update_by
	 * @param updateBy  the value for nj_product_tactics_property.update_by
	 * @mbg.generated  Wed Mar 29 15:17:29 CST 2017
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}