package com.nj.model.generate;

import com.nj.model.generate.NjProductType;
import com.nj.model.generate.NjProductTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NjProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    long countByExample(NjProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int deleteByExample(NjProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int insert(NjProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int insertSelective(NjProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    List<NjProductType> selectByExample(NjProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    NjProductType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") NjProductType record, @Param("example") NjProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int updateByExample(@Param("record") NjProductType record, @Param("example") NjProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int updateByPrimaryKeySelective(NjProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nj_product_type
     *
     * @mbg.generated Tue Feb 28 11:23:17 CST 2017
     */
    int updateByPrimaryKey(NjProductType record);
}