package com.nj.model.generate;

import java.util.Date;

public class NjPushTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.createBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.createTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.deleteTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date deletetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.isDeleted
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Boolean isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.updateBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String updateby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.updateTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.template
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String template;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_push_template.aliCode
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String alicode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.id
	 * @return  the value of nj_push_template.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.id
	 * @param id  the value for nj_push_template.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.createBy
	 * @return  the value of nj_push_template.createBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.createBy
	 * @param createby  the value for nj_push_template.createBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.createTime
	 * @return  the value of nj_push_template.createTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.createTime
	 * @param createtime  the value for nj_push_template.createTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.deleteTime
	 * @return  the value of nj_push_template.deleteTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getDeletetime() {
		return deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.deleteTime
	 * @param deletetime  the value for nj_push_template.deleteTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setDeletetime(Date deletetime) {
		this.deletetime = deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.isDeleted
	 * @return  the value of nj_push_template.isDeleted
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Boolean getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.isDeleted
	 * @param isdeleted  the value for nj_push_template.isDeleted
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.updateBy
	 * @return  the value of nj_push_template.updateBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.updateBy
	 * @param updateby  the value for nj_push_template.updateBy
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.updateTime
	 * @return  the value of nj_push_template.updateTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.updateTime
	 * @param updatetime  the value for nj_push_template.updateTime
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.version
	 * @return  the value of nj_push_template.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.version
	 * @param version  the value for nj_push_template.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.code
	 * @return  the value of nj_push_template.code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.code
	 * @param code  the value for nj_push_template.code
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.name
	 * @return  the value of nj_push_template.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.name
	 * @param name  the value for nj_push_template.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.template
	 * @return  the value of nj_push_template.template
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getTemplate() {
		return template;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.template
	 * @param template  the value for nj_push_template.template
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setTemplate(String template) {
		this.template = template;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_push_template.aliCode
	 * @return  the value of nj_push_template.aliCode
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getAlicode() {
		return alicode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_push_template.aliCode
	 * @param alicode  the value for nj_push_template.aliCode
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setAlicode(String alicode) {
		this.alicode = alicode;
	}
}