package com.nj.model.generate;

import java.util.Date;

public class NjSmsSetting {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.is_open_sms
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer isOpenSms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.sms_pwd
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String smsPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.sms_url
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String smsUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.sms_username
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String smsUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Boolean delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_sms_setting.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.id
	 * @return  the value of nj_sms_setting.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.id
	 * @param id  the value for nj_sms_setting.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.version
	 * @return  the value of nj_sms_setting.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.version
	 * @param version  the value for nj_sms_setting.version
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.is_open_sms
	 * @return  the value of nj_sms_setting.is_open_sms
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getIsOpenSms() {
		return isOpenSms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.is_open_sms
	 * @param isOpenSms  the value for nj_sms_setting.is_open_sms
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setIsOpenSms(Integer isOpenSms) {
		this.isOpenSms = isOpenSms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.sms_pwd
	 * @return  the value of nj_sms_setting.sms_pwd
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getSmsPwd() {
		return smsPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.sms_pwd
	 * @param smsPwd  the value for nj_sms_setting.sms_pwd
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setSmsPwd(String smsPwd) {
		this.smsPwd = smsPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.sms_url
	 * @return  the value of nj_sms_setting.sms_url
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getSmsUrl() {
		return smsUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.sms_url
	 * @param smsUrl  the value for nj_sms_setting.sms_url
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setSmsUrl(String smsUrl) {
		this.smsUrl = smsUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.sms_username
	 * @return  the value of nj_sms_setting.sms_username
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getSmsUsername() {
		return smsUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.sms_username
	 * @param smsUsername  the value for nj_sms_setting.sms_username
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setSmsUsername(String smsUsername) {
		this.smsUsername = smsUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.del_flag
	 * @return  the value of nj_sms_setting.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.del_flag
	 * @param delFlag  the value for nj_sms_setting.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.create_date
	 * @return  the value of nj_sms_setting.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.create_date
	 * @param createDate  the value for nj_sms_setting.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.create_by
	 * @return  the value of nj_sms_setting.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.create_by
	 * @param createBy  the value for nj_sms_setting.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.update_date
	 * @return  the value of nj_sms_setting.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.update_date
	 * @param updateDate  the value for nj_sms_setting.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_sms_setting.update_by
	 * @return  the value of nj_sms_setting.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_sms_setting.update_by
	 * @param updateBy  the value for nj_sms_setting.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}