package com.nj.model.generate;

import java.math.BigDecimal;

public class NjStatisticsSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.compan_id
     *
     * @mbggenerated
     */
    private String companId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.compan_code
     *
     * @mbggenerated
     */
    private String companCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.compan_name
     *
     * @mbggenerated
     */
    private String companName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.loan_num
     *
     * @mbggenerated
     */
    private String loanNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.loan_amount
     *
     * @mbggenerated
     */
    private BigDecimal loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.overdue_amount
     *
     * @mbggenerated
     */
    private BigDecimal overdueAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.loan_user_count
     *
     * @mbggenerated
     */
    private String loanUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.first_amount_range_count
     *
     * @mbggenerated
     */
    private String firstAmountRangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.first_amount_range_sum
     *
     * @mbggenerated
     */
    private BigDecimal firstAmountRangeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.second_amount_range_count
     *
     * @mbggenerated
     */
    private String secondAmountRangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.second_amount_range_sum
     *
     * @mbggenerated
     */
    private BigDecimal secondAmountRangeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.third_amount_range_count
     *
     * @mbggenerated
     */
    private String thirdAmountRangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.third_amount_range_sum
     *
     * @mbggenerated
     */
    private BigDecimal thirdAmountRangeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.fourth_amount_range_count
     *
     * @mbggenerated
     */
    private String fourthAmountRangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.fourth_amount_range_sum
     *
     * @mbggenerated
     */
    private BigDecimal fourthAmountRangeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.fifth_amount_range_count
     *
     * @mbggenerated
     */
    private String fifthAmountRangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.fifth_amount_range_sum
     *
     * @mbggenerated
     */
    private BigDecimal fifthAmountRangeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nj_statistics_summary.due_date
     *
     * @mbggenerated
     */
    private String dueDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.id
     *
     * @return the value of nj_statistics_summary.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.id
     *
     * @param id the value for nj_statistics_summary.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.compan_id
     *
     * @return the value of nj_statistics_summary.compan_id
     *
     * @mbggenerated
     */
    public String getCompanId() {
        return companId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.compan_id
     *
     * @param companId the value for nj_statistics_summary.compan_id
     *
     * @mbggenerated
     */
    public void setCompanId(String companId) {
        this.companId = companId == null ? null : companId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.compan_code
     *
     * @return the value of nj_statistics_summary.compan_code
     *
     * @mbggenerated
     */
    public String getCompanCode() {
        return companCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.compan_code
     *
     * @param companCode the value for nj_statistics_summary.compan_code
     *
     * @mbggenerated
     */
    public void setCompanCode(String companCode) {
        this.companCode = companCode == null ? null : companCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.compan_name
     *
     * @return the value of nj_statistics_summary.compan_name
     *
     * @mbggenerated
     */
    public String getCompanName() {
        return companName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.compan_name
     *
     * @param companName the value for nj_statistics_summary.compan_name
     *
     * @mbggenerated
     */
    public void setCompanName(String companName) {
        this.companName = companName == null ? null : companName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.loan_num
     *
     * @return the value of nj_statistics_summary.loan_num
     *
     * @mbggenerated
     */
    public String getLoanNum() {
        return loanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.loan_num
     *
     * @param loanNum the value for nj_statistics_summary.loan_num
     *
     * @mbggenerated
     */
    public void setLoanNum(String loanNum) {
        this.loanNum = loanNum == null ? null : loanNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.loan_amount
     *
     * @return the value of nj_statistics_summary.loan_amount
     *
     * @mbggenerated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.loan_amount
     *
     * @param loanAmount the value for nj_statistics_summary.loan_amount
     *
     * @mbggenerated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.overdue_amount
     *
     * @return the value of nj_statistics_summary.overdue_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOverdueAmount() {
        return overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.overdue_amount
     *
     * @param overdueAmount the value for nj_statistics_summary.overdue_amount
     *
     * @mbggenerated
     */
    public void setOverdueAmount(BigDecimal overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.loan_user_count
     *
     * @return the value of nj_statistics_summary.loan_user_count
     *
     * @mbggenerated
     */
    public String getLoanUserCount() {
        return loanUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.loan_user_count
     *
     * @param loanUserCount the value for nj_statistics_summary.loan_user_count
     *
     * @mbggenerated
     */
    public void setLoanUserCount(String loanUserCount) {
        this.loanUserCount = loanUserCount == null ? null : loanUserCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.first_amount_range_count
     *
     * @return the value of nj_statistics_summary.first_amount_range_count
     *
     * @mbggenerated
     */
    public String getFirstAmountRangeCount() {
        return firstAmountRangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.first_amount_range_count
     *
     * @param firstAmountRangeCount the value for nj_statistics_summary.first_amount_range_count
     *
     * @mbggenerated
     */
    public void setFirstAmountRangeCount(String firstAmountRangeCount) {
        this.firstAmountRangeCount = firstAmountRangeCount == null ? null : firstAmountRangeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.first_amount_range_sum
     *
     * @return the value of nj_statistics_summary.first_amount_range_sum
     *
     * @mbggenerated
     */
    public BigDecimal getFirstAmountRangeSum() {
        return firstAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.first_amount_range_sum
     *
     * @param firstAmountRangeSum the value for nj_statistics_summary.first_amount_range_sum
     *
     * @mbggenerated
     */
    public void setFirstAmountRangeSum(BigDecimal firstAmountRangeSum) {
        this.firstAmountRangeSum = firstAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.second_amount_range_count
     *
     * @return the value of nj_statistics_summary.second_amount_range_count
     *
     * @mbggenerated
     */
    public String getSecondAmountRangeCount() {
        return secondAmountRangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.second_amount_range_count
     *
     * @param secondAmountRangeCount the value for nj_statistics_summary.second_amount_range_count
     *
     * @mbggenerated
     */
    public void setSecondAmountRangeCount(String secondAmountRangeCount) {
        this.secondAmountRangeCount = secondAmountRangeCount == null ? null : secondAmountRangeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.second_amount_range_sum
     *
     * @return the value of nj_statistics_summary.second_amount_range_sum
     *
     * @mbggenerated
     */
    public BigDecimal getSecondAmountRangeSum() {
        return secondAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.second_amount_range_sum
     *
     * @param secondAmountRangeSum the value for nj_statistics_summary.second_amount_range_sum
     *
     * @mbggenerated
     */
    public void setSecondAmountRangeSum(BigDecimal secondAmountRangeSum) {
        this.secondAmountRangeSum = secondAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.third_amount_range_count
     *
     * @return the value of nj_statistics_summary.third_amount_range_count
     *
     * @mbggenerated
     */
    public String getThirdAmountRangeCount() {
        return thirdAmountRangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.third_amount_range_count
     *
     * @param thirdAmountRangeCount the value for nj_statistics_summary.third_amount_range_count
     *
     * @mbggenerated
     */
    public void setThirdAmountRangeCount(String thirdAmountRangeCount) {
        this.thirdAmountRangeCount = thirdAmountRangeCount == null ? null : thirdAmountRangeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.third_amount_range_sum
     *
     * @return the value of nj_statistics_summary.third_amount_range_sum
     *
     * @mbggenerated
     */
    public BigDecimal getThirdAmountRangeSum() {
        return thirdAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.third_amount_range_sum
     *
     * @param thirdAmountRangeSum the value for nj_statistics_summary.third_amount_range_sum
     *
     * @mbggenerated
     */
    public void setThirdAmountRangeSum(BigDecimal thirdAmountRangeSum) {
        this.thirdAmountRangeSum = thirdAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.fourth_amount_range_count
     *
     * @return the value of nj_statistics_summary.fourth_amount_range_count
     *
     * @mbggenerated
     */
    public String getFourthAmountRangeCount() {
        return fourthAmountRangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.fourth_amount_range_count
     *
     * @param fourthAmountRangeCount the value for nj_statistics_summary.fourth_amount_range_count
     *
     * @mbggenerated
     */
    public void setFourthAmountRangeCount(String fourthAmountRangeCount) {
        this.fourthAmountRangeCount = fourthAmountRangeCount == null ? null : fourthAmountRangeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.fourth_amount_range_sum
     *
     * @return the value of nj_statistics_summary.fourth_amount_range_sum
     *
     * @mbggenerated
     */
    public BigDecimal getFourthAmountRangeSum() {
        return fourthAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.fourth_amount_range_sum
     *
     * @param fourthAmountRangeSum the value for nj_statistics_summary.fourth_amount_range_sum
     *
     * @mbggenerated
     */
    public void setFourthAmountRangeSum(BigDecimal fourthAmountRangeSum) {
        this.fourthAmountRangeSum = fourthAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.fifth_amount_range_count
     *
     * @return the value of nj_statistics_summary.fifth_amount_range_count
     *
     * @mbggenerated
     */
    public String getFifthAmountRangeCount() {
        return fifthAmountRangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.fifth_amount_range_count
     *
     * @param fifthAmountRangeCount the value for nj_statistics_summary.fifth_amount_range_count
     *
     * @mbggenerated
     */
    public void setFifthAmountRangeCount(String fifthAmountRangeCount) {
        this.fifthAmountRangeCount = fifthAmountRangeCount == null ? null : fifthAmountRangeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.fifth_amount_range_sum
     *
     * @return the value of nj_statistics_summary.fifth_amount_range_sum
     *
     * @mbggenerated
     */
    public BigDecimal getFifthAmountRangeSum() {
        return fifthAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.fifth_amount_range_sum
     *
     * @param fifthAmountRangeSum the value for nj_statistics_summary.fifth_amount_range_sum
     *
     * @mbggenerated
     */
    public void setFifthAmountRangeSum(BigDecimal fifthAmountRangeSum) {
        this.fifthAmountRangeSum = fifthAmountRangeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nj_statistics_summary.due_date
     *
     * @return the value of nj_statistics_summary.due_date
     *
     * @mbggenerated
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nj_statistics_summary.due_date
     *
     * @param dueDate the value for nj_statistics_summary.due_date
     *
     * @mbggenerated
     */
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate == null ? null : dueDate.trim();
    }
}