package com.nj.model.generate;

import java.io.Serializable;
import java.util.Date;

public class NjUserRelatives implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.version
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.relative_mobile
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String relativeMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.relative_name
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String relativeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.relative_type
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String relativeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.user_id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.remarks
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.create_date
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nj_user_relatives.del_flag
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	private Byte delFlag;
	
	 /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.province
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String province;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.city
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String city;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.county
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String county;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.address
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String address;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.sex
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private Integer sex;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.org_name
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String orgName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.profession
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String profession;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.nation
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String nation;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.id_card_num
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private String idCardNum;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column nj_user_relatives.age
    *
    * @mbg.generated Fri Jun 22 18:19:10 CST 2018
    */
   private Integer age;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.id
	 * @return  the value of nj_user_relatives.id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.id
	 * @param id  the value for nj_user_relatives.id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.version
	 * @return  the value of nj_user_relatives.version
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.version
	 * @param version  the value for nj_user_relatives.version
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.relative_mobile
	 * @return  the value of nj_user_relatives.relative_mobile
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getRelativeMobile() {
		return relativeMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.relative_mobile
	 * @param relativeMobile  the value for nj_user_relatives.relative_mobile
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setRelativeMobile(String relativeMobile) {
		this.relativeMobile = relativeMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.relative_name
	 * @return  the value of nj_user_relatives.relative_name
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getRelativeName() {
		return relativeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.relative_name
	 * @param relativeName  the value for nj_user_relatives.relative_name
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setRelativeName(String relativeName) {
		this.relativeName = relativeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.relative_type
	 * @return  the value of nj_user_relatives.relative_type
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getRelativeType() {
		return relativeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.relative_type
	 * @param relativeType  the value for nj_user_relatives.relative_type
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setRelativeType(String relativeType) {
		this.relativeType = relativeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.user_id
	 * @return  the value of nj_user_relatives.user_id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.user_id
	 * @param userId  the value for nj_user_relatives.user_id
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.remarks
	 * @return  the value of nj_user_relatives.remarks
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.remarks
	 * @param remarks  the value for nj_user_relatives.remarks
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.create_date
	 * @return  the value of nj_user_relatives.create_date
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.create_date
	 * @param createDate  the value for nj_user_relatives.create_date
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nj_user_relatives.del_flag
	 * @return  the value of nj_user_relatives.del_flag
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nj_user_relatives.del_flag
	 * @param delFlag  the value for nj_user_relatives.del_flag
	 * @mbg.generated  Thu Mar 09 15:36:15 CST 2017
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getProfession() {
		return profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getIdCardNum() {
		return idCardNum;
	}

	public void setIdCardNum(String idCardNum) {
		this.idCardNum = idCardNum;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}
	
	
}