package com.nj.model.generate;

import java.util.ArrayList;
import java.util.List;

public class StockFormatDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public StockFormatDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNull() {
            addCriterion("dict_id is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("dict_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(String value) {
            addCriterion("dict_id =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(String value) {
            addCriterion("dict_id <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(String value) {
            addCriterion("dict_id >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_id >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(String value) {
            addCriterion("dict_id <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(String value) {
            addCriterion("dict_id <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLike(String value) {
            addCriterion("dict_id like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotLike(String value) {
            addCriterion("dict_id not like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<String> values) {
            addCriterion("dict_id in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<String> values) {
            addCriterion("dict_id not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(String value1, String value2) {
            addCriterion("dict_id between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(String value1, String value2) {
            addCriterion("dict_id not between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andColumNameIsNull() {
            addCriterion("colum_name is null");
            return (Criteria) this;
        }

        public Criteria andColumNameIsNotNull() {
            addCriterion("colum_name is not null");
            return (Criteria) this;
        }

        public Criteria andColumNameEqualTo(String value) {
            addCriterion("colum_name =", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameNotEqualTo(String value) {
            addCriterion("colum_name <>", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameGreaterThan(String value) {
            addCriterion("colum_name >", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameGreaterThanOrEqualTo(String value) {
            addCriterion("colum_name >=", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameLessThan(String value) {
            addCriterion("colum_name <", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameLessThanOrEqualTo(String value) {
            addCriterion("colum_name <=", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameLike(String value) {
            addCriterion("colum_name like", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameNotLike(String value) {
            addCriterion("colum_name not like", value, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameIn(List<String> values) {
            addCriterion("colum_name in", values, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameNotIn(List<String> values) {
            addCriterion("colum_name not in", values, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameBetween(String value1, String value2) {
            addCriterion("colum_name between", value1, value2, "columName");
            return (Criteria) this;
        }

        public Criteria andColumNameNotBetween(String value1, String value2) {
            addCriterion("colum_name not between", value1, value2, "columName");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdIsNull() {
            addCriterion("stock_format_id is null");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdIsNotNull() {
            addCriterion("stock_format_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdEqualTo(String value) {
            addCriterion("stock_format_id =", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdNotEqualTo(String value) {
            addCriterion("stock_format_id <>", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdGreaterThan(String value) {
            addCriterion("stock_format_id >", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdGreaterThanOrEqualTo(String value) {
            addCriterion("stock_format_id >=", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdLessThan(String value) {
            addCriterion("stock_format_id <", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdLessThanOrEqualTo(String value) {
            addCriterion("stock_format_id <=", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdLike(String value) {
            addCriterion("stock_format_id like", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdNotLike(String value) {
            addCriterion("stock_format_id not like", value, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdIn(List<String> values) {
            addCriterion("stock_format_id in", values, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdNotIn(List<String> values) {
            addCriterion("stock_format_id not in", values, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdBetween(String value1, String value2) {
            addCriterion("stock_format_id between", value1, value2, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andStockFormatIdNotBetween(String value1, String value2) {
            addCriterion("stock_format_id not between", value1, value2, "stockFormatId");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_format_dict
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 11 16:56:05 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_format_dict
     *
     * @mbggenerated Mon Jan 11 16:56:05 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}