package com.nj.model.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public SysLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrIsNull() {
			addCriterion("remote_addr is null");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrIsNotNull() {
			addCriterion("remote_addr is not null");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrEqualTo(String value) {
			addCriterion("remote_addr =", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrNotEqualTo(String value) {
			addCriterion("remote_addr <>", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrGreaterThan(String value) {
			addCriterion("remote_addr >", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrGreaterThanOrEqualTo(String value) {
			addCriterion("remote_addr >=", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrLessThan(String value) {
			addCriterion("remote_addr <", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrLessThanOrEqualTo(String value) {
			addCriterion("remote_addr <=", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrLike(String value) {
			addCriterion("remote_addr like", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrNotLike(String value) {
			addCriterion("remote_addr not like", value, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrIn(List<String> values) {
			addCriterion("remote_addr in", values, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrNotIn(List<String> values) {
			addCriterion("remote_addr not in", values, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrBetween(String value1, String value2) {
			addCriterion("remote_addr between", value1, value2, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andRemoteAddrNotBetween(String value1, String value2) {
			addCriterion("remote_addr not between", value1, value2, "remoteAddr");
			return (Criteria) this;
		}

		public Criteria andUserAgentIsNull() {
			addCriterion("user_agent is null");
			return (Criteria) this;
		}

		public Criteria andUserAgentIsNotNull() {
			addCriterion("user_agent is not null");
			return (Criteria) this;
		}

		public Criteria andUserAgentEqualTo(String value) {
			addCriterion("user_agent =", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotEqualTo(String value) {
			addCriterion("user_agent <>", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentGreaterThan(String value) {
			addCriterion("user_agent >", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentGreaterThanOrEqualTo(String value) {
			addCriterion("user_agent >=", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLessThan(String value) {
			addCriterion("user_agent <", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLessThanOrEqualTo(String value) {
			addCriterion("user_agent <=", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLike(String value) {
			addCriterion("user_agent like", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotLike(String value) {
			addCriterion("user_agent not like", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentIn(List<String> values) {
			addCriterion("user_agent in", values, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotIn(List<String> values) {
			addCriterion("user_agent not in", values, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentBetween(String value1, String value2) {
			addCriterion("user_agent between", value1, value2, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotBetween(String value1, String value2) {
			addCriterion("user_agent not between", value1, value2, "userAgent");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andRequestUriIsNull() {
			addCriterion("request_uri is null");
			return (Criteria) this;
		}

		public Criteria andRequestUriIsNotNull() {
			addCriterion("request_uri is not null");
			return (Criteria) this;
		}

		public Criteria andRequestUriEqualTo(String value) {
			addCriterion("request_uri =", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriNotEqualTo(String value) {
			addCriterion("request_uri <>", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriGreaterThan(String value) {
			addCriterion("request_uri >", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriGreaterThanOrEqualTo(String value) {
			addCriterion("request_uri >=", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriLessThan(String value) {
			addCriterion("request_uri <", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriLessThanOrEqualTo(String value) {
			addCriterion("request_uri <=", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriLike(String value) {
			addCriterion("request_uri like", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriNotLike(String value) {
			addCriterion("request_uri not like", value, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriIn(List<String> values) {
			addCriterion("request_uri in", values, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriNotIn(List<String> values) {
			addCriterion("request_uri not in", values, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriBetween(String value1, String value2) {
			addCriterion("request_uri between", value1, value2, "requestUri");
			return (Criteria) this;
		}

		public Criteria andRequestUriNotBetween(String value1, String value2) {
			addCriterion("request_uri not between", value1, value2, "requestUri");
			return (Criteria) this;
		}

		public Criteria andMethodIsNull() {
			addCriterion("method is null");
			return (Criteria) this;
		}

		public Criteria andMethodIsNotNull() {
			addCriterion("method is not null");
			return (Criteria) this;
		}

		public Criteria andMethodEqualTo(String value) {
			addCriterion("method =", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodNotEqualTo(String value) {
			addCriterion("method <>", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodGreaterThan(String value) {
			addCriterion("method >", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodGreaterThanOrEqualTo(String value) {
			addCriterion("method >=", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodLessThan(String value) {
			addCriterion("method <", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodLessThanOrEqualTo(String value) {
			addCriterion("method <=", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodLike(String value) {
			addCriterion("method like", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodNotLike(String value) {
			addCriterion("method not like", value, "method");
			return (Criteria) this;
		}

		public Criteria andMethodIn(List<String> values) {
			addCriterion("method in", values, "method");
			return (Criteria) this;
		}

		public Criteria andMethodNotIn(List<String> values) {
			addCriterion("method not in", values, "method");
			return (Criteria) this;
		}

		public Criteria andMethodBetween(String value1, String value2) {
			addCriterion("method between", value1, value2, "method");
			return (Criteria) this;
		}

		public Criteria andMethodNotBetween(String value1, String value2) {
			addCriterion("method not between", value1, value2, "method");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNull() {
			addCriterion("request_id is null");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNotNull() {
			addCriterion("request_id is not null");
			return (Criteria) this;
		}

		public Criteria andRequestIdEqualTo(String value) {
			addCriterion("request_id =", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotEqualTo(String value) {
			addCriterion("request_id <>", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThan(String value) {
			addCriterion("request_id >", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
			addCriterion("request_id >=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThan(String value) {
			addCriterion("request_id <", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThanOrEqualTo(String value) {
			addCriterion("request_id <=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLike(String value) {
			addCriterion("request_id like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotLike(String value) {
			addCriterion("request_id not like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdIn(List<String> values) {
			addCriterion("request_id in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotIn(List<String> values) {
			addCriterion("request_id not in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdBetween(String value1, String value2) {
			addCriterion("request_id between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotBetween(String value1, String value2) {
			addCriterion("request_id not between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestDateIsNull() {
			addCriterion("request_date is null");
			return (Criteria) this;
		}

		public Criteria andRequestDateIsNotNull() {
			addCriterion("request_date is not null");
			return (Criteria) this;
		}

		public Criteria andRequestDateEqualTo(Date value) {
			addCriterion("request_date =", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateNotEqualTo(Date value) {
			addCriterion("request_date <>", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateGreaterThan(Date value) {
			addCriterion("request_date >", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateGreaterThanOrEqualTo(Date value) {
			addCriterion("request_date >=", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateLessThan(Date value) {
			addCriterion("request_date <", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateLessThanOrEqualTo(Date value) {
			addCriterion("request_date <=", value, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateIn(List<Date> values) {
			addCriterion("request_date in", values, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateNotIn(List<Date> values) {
			addCriterion("request_date not in", values, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateBetween(Date value1, Date value2) {
			addCriterion("request_date between", value1, value2, "requestDate");
			return (Criteria) this;
		}

		public Criteria andRequestDateNotBetween(Date value1, Date value2) {
			addCriterion("request_date not between", value1, value2, "requestDate");
			return (Criteria) this;
		}

		public Criteria andLogTypeIsNull() {
			addCriterion("log_type is null");
			return (Criteria) this;
		}

		public Criteria andLogTypeIsNotNull() {
			addCriterion("log_type is not null");
			return (Criteria) this;
		}

		public Criteria andLogTypeEqualTo(Integer value) {
			addCriterion("log_type =", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotEqualTo(Integer value) {
			addCriterion("log_type <>", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThan(Integer value) {
			addCriterion("log_type >", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_type >=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThan(Integer value) {
			addCriterion("log_type <", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThanOrEqualTo(Integer value) {
			addCriterion("log_type <=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeIn(List<Integer> values) {
			addCriterion("log_type in", values, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotIn(List<Integer> values) {
			addCriterion("log_type not in", values, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeBetween(Integer value1, Integer value2) {
			addCriterion("log_type between", value1, value2, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("log_type not between", value1, value2, "logType");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(String value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(String value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(String value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(String value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(String value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLike(String value) {
			addCriterion("create_by like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotLike(String value) {
			addCriterion("create_by not like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<String> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<String> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(String value1, String value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(String value1, String value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_log
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_log
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 15 14:14:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}