package com.nj.model.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysResource {
	
	public enum IsShow{
		LOAN("2"),ADMIN("1"),RIGHT("3");
		
		private String value;
		private IsShow(String value) {
			this.value = value;
		}
		
		public String getValue(){
			return value;
		}
	}
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.parent_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.parent_ids
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String parentIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.sort
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.href
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String href;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.target
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.icon
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.is_show
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 * 1：表示该资源是管理后台的     2:表示该资源是金鼎微贷的
	 */
	private String isShow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.permission
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.remarks
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	private Boolean delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.id
	 * @return  the value of sys_resource.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.id
	 * @param id  the value for sys_resource.id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.parent_id
	 * @return  the value of sys_resource.parent_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.parent_id
	 * @param parentId  the value for sys_resource.parent_id
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.parent_ids
	 * @return  the value of sys_resource.parent_ids
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getParentIds() {
		return parentIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.parent_ids
	 * @param parentIds  the value for sys_resource.parent_ids
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.name
	 * @return  the value of sys_resource.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.name
	 * @param name  the value for sys_resource.name
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.sort
	 * @return  the value of sys_resource.sort
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.sort
	 * @param sort  the value for sys_resource.sort
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.href
	 * @return  the value of sys_resource.href
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getHref() {
		return href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.href
	 * @param href  the value for sys_resource.href
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setHref(String href) {
		this.href = href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.target
	 * @return  the value of sys_resource.target
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.target
	 * @param target  the value for sys_resource.target
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.icon
	 * @return  the value of sys_resource.icon
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.icon
	 * @param icon  the value for sys_resource.icon
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.is_show
	 * @return  the value of sys_resource.is_show
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.is_show
	 * @param isShow  the value for sys_resource.is_show
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.permission
	 * @return  the value of sys_resource.permission
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.permission
	 * @param permission  the value for sys_resource.permission
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.create_by
	 * @return  the value of sys_resource.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.create_by
	 * @param createBy  the value for sys_resource.create_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.create_date
	 * @return  the value of sys_resource.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.create_date
	 * @param createDate  the value for sys_resource.create_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.update_by
	 * @return  the value of sys_resource.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.update_by
	 * @param updateBy  the value for sys_resource.update_by
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.update_date
	 * @return  the value of sys_resource.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.update_date
	 * @param updateDate  the value for sys_resource.update_date
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.remarks
	 * @return  the value of sys_resource.remarks
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.remarks
	 * @param remarks  the value for sys_resource.remarks
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.del_flag
	 * @return  the value of sys_resource.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.del_flag
	 * @param delFlag  the value for sys_resource.del_flag
	 * @mbg.generated  Tue Mar 07 15:58:03 CST 2017
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	private List<SysResource> subList = new ArrayList<>();

    public List<SysResource> getSubList() {
		return subList;
	}

	public void setSubList(List<SysResource> subList) {
		this.subList = subList;
	}
}