package com.nj.model.generate;

import java.util.Date;

public class SysUpdateTableLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.update_table
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String updateTable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.update_table_id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String updateTableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.update_time
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.update_type
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String updateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.operator
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_update_table_log.remark
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.id
	 * @return  the value of sys_update_table_log.id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.id
	 * @param id  the value for sys_update_table_log.id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.update_table
	 * @return  the value of sys_update_table_log.update_table
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getUpdateTable() {
		return updateTable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.update_table
	 * @param updateTable  the value for sys_update_table_log.update_table
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setUpdateTable(String updateTable) {
		this.updateTable = updateTable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.update_table_id
	 * @return  the value of sys_update_table_log.update_table_id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getUpdateTableId() {
		return updateTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.update_table_id
	 * @param updateTableId  the value for sys_update_table_log.update_table_id
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setUpdateTableId(String updateTableId) {
		this.updateTableId = updateTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.update_time
	 * @return  the value of sys_update_table_log.update_time
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.update_time
	 * @param updateTime  the value for sys_update_table_log.update_time
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.update_type
	 * @return  the value of sys_update_table_log.update_type
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getUpdateType() {
		return updateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.update_type
	 * @param updateType  the value for sys_update_table_log.update_type
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setUpdateType(String updateType) {
		this.updateType = updateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.operator
	 * @return  the value of sys_update_table_log.operator
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.operator
	 * @param operator  the value for sys_update_table_log.operator
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_update_table_log.remark
	 * @return  the value of sys_update_table_log.remark
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_update_table_log.remark
	 * @param remark  the value for sys_update_table_log.remark
	 * @mbg.generated  Wed May 10 15:03:11 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}