package com.nj.model.generate;

import java.util.Date;

public class ZhimaScoreLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhima_score_log.id
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhima_score_log.score
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhima_score_log.biz_no
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    private String bizNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhima_score_log.create_date
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhima_score_log.result
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhima_score_log.id
     *
     * @return the value of zhima_score_log.id
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhima_score_log.id
     *
     * @param id the value for zhima_score_log.id
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhima_score_log.score
     *
     * @return the value of zhima_score_log.score
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhima_score_log.score
     *
     * @param score the value for zhima_score_log.score
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhima_score_log.biz_no
     *
     * @return the value of zhima_score_log.biz_no
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhima_score_log.biz_no
     *
     * @param bizNo the value for zhima_score_log.biz_no
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhima_score_log.create_date
     *
     * @return the value of zhima_score_log.create_date
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhima_score_log.create_date
     *
     * @param createDate the value for zhima_score_log.create_date
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhima_score_log.result
     *
     * @return the value of zhima_score_log.result
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhima_score_log.result
     *
     * @param result the value for zhima_score_log.result
     *
     * @mbg.generated Tue Mar 14 19:03:45 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }
}